### ISSUE TITLE
Debian install installs libksi.so.5 as non-symlink

### ISSUE THREAD

**Issue by TomMD** [GuardTime/libksi#11]
It is an error, in the eyes of ldconfig, to install general version numbers as actual files instead of symlinks to the concrete version (`libksi.so.5` is a concrete file instead of soft link to `libksi.so.5.0.0` in this case).  As a result of the generated .deb installing concrete files instead of links the linker does not find the library without some extra trickery (removing the offending file or setting LD_LIBRARY_PATH).

Yes, I know the Debian package is not officially supported.  Consider this issue report an FYI.

**Comment by taavi-valjaots** [comment]
Issue is fixed in release 3.15.2306.
