### ISSUE TITLE
Broken markdown used in tutorials

### ISSUE THREAD

**Issue by TomMD** [GuardTime/libksi#6]
The markdown appears to be a different dialect than Github-markdown.  As a result, the files present with syntactic extra's such as `\c` prior to `c` code and broken links, such as the link from tutorial t1 to t0.

**Comment by vii5ard** [comment]
The markdown used in the tutorials is not intended to be used directly from github, they are used as input for doxygen (=<1.8.0). Please use the generated document instead (http://guardtime.github.io/libksi/3.9/)
