### ISSUE TITLE
Const-ness needs corrected on signature parse

### ISSUE THREAD

**Issue by TomMD** [GuardTime/libksi#9]
Note

```
        int KSI_Signature_parse(KSI_CTX *ctx, unsigned char *raw, size_t raw_len, KSI_Signature **sig);
```

Should probably be:

```
        int KSI_Signature_parse(KSI_CTX *ctx, const unsigned char *raw, size_t raw_len, KSI_Signature **sig);
```

Since paying attention to `const`ness often happens in bulk should I bother issuing more reports like this or just leave this issue open in place of a more complete `const`-ification of the code base?

**Comment by margoraja** [comment]
Will leave this issue open for now, no need to create new reports.

**Comment by vii5ard** [comment]
This issue was fixed in release v.3.12.2000 (6c1837f).
